version: 0.0

containers:
  main:
    phases:
      install:
        commands:
          - apt-get update -y
          - apt-get install -y maven
      during_build:
        commands:
          - echo Build started on `date`
          - mvn test
          - mvn package 
      post_build:
        commands:
          - echo Build completed on `date`
    artifacts:
      type: zip
      files:
        - target/my-app-1.0-SNAPSHOT.jar
